create table
  public.users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone null,
    address character varying not null,
    config json null,
    income json null,
    user_level smallint null default '0'::smallint,
    username text null,
    email text null,
    constraint users_pkey primary key (id, address)
  ) tablespace pg_default;